- hosts: localhost
  vars_prompt:
          - name: container_name
            prompt: "Enter the name of docker container:"
            private: no

  tasks:
           - name: Configuring the yum repo for Docker
             yum_repository:
                     name: Docker
                     file: docker
                     description: docker repo
                     baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                     gpgcheck: no

           - name: "Installing Docker"
             pip:
                     name: "docker"

           - name: Installing Docker community edition
             package:
                     name: "docker-ce-18.09.1-3.el7.x86_64"
                     state: present

           - name: "Pulling httpd image"
             docker_image:
                     name: "httpd"
                     source: pull

           - name: Launching httpd {{container_name}}container
             docker_container:
                      name: "{{container_name}}"
                      image: "httpd"
                      state: started
                      volumes: "/var/www/html/:/usr/local/apache2/htdocs"

             register: dock
           - debug:
                    var: dock.container.NetworkSettings.IPAddress

           - name: Updating the inventory dynamically
             blockinfile:
                      block: |
                              [docker]
                              {{ dock.container.NetworkSettings.IPAddress }} ansible_ssh_user=root ansible_ssh_pass=sherlock ansible_connection=ssh
                      path: "/etc/ansible/ip.txt"
- hosts: docker
  tasks:
  - name: Installing httpd
    package:
            name: "httpd"
            state: present

  - name: Starting httpd
    service:
            name: "httpd"
            state: started

